### ISSUE TITLE
Kaku doesn't start

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#453]
#### Bug

Kaku stuck at "Loading"

#### Steps to reproduce the bug

Run Kaku

#### What is your Kaku version ?

dd9f06d8985cf3bf2a90fd7c304128d8d1b21c4e

#### What is your OS with version number ?

Linux debian 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
(Debian Stretch with GNOME)

#### Which platform you are using to listen to music ?

YouTube (but not important)

#### Which track format you are using ?

best audio (but not important)

#### Is there any error coming from Inspector ?

/home/michel/git/Kaku/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:1 Uncaught Error: Cannot find module 'React'

**Comment by neighborhood999** [comment]
I have the same problem on Ubuntu 14.04.
In previous version, I run `npm rebuild` can solved this problem, but now it can't.

**Comment by EragonJ** [comment]
@mimi89999 can you try to use `git bisect` and see which commit caused that problem because I can't reproduce that in my laptop (macOS)

**Comment by mimi89999** [comment]
@EragonJ Could you clone the repo somewhere on you PC (somewhere else than the current location) and do all the steps to build Kaku? We could then know if it is a problem with Kaku on GNU/Linux, with some piece of code, that wasn't commited for some reason (like the index.html) or with a module that doesn't work now.

**Comment by EragonJ** [comment]
working fine, just like what I commented on wiki, needs to run `npm i` twice and that's it. Right now `node-youtube-dl` is buggy and can't be installed successfully on the first round.

**Comment by EragonJ** [comment]
@mimi89999 ^ plz check this

**Comment by mimi89999** [comment]
I am always executing `npm i` twice...

**Comment by EragonJ** [comment]
@mimi89999 

`npm i` twice is not the main problem that related to your issue, is there any other error showing up when you try to do `npm i` ?

I think this may be related to differences of OS when building some special modules.

**Comment by EragonJ** [comment]
@mimi89999 @neighborhood999 just pinged me that it's working now on his laptop with the same env like you. Any idea about that ?

**Comment by mimi89999** [comment]
@EragonJ I confirm, that Kaku works now.

**Comment by EragonJ** [comment]
@mimi89999 can you help me to bisect from dd9f06d to latest master and see which commit fixed the issue ? I cant understand which commit fixed the issue to be honest Q_Q

**Comment by neighborhood999** [comment]
@EragonJ I already checkout **dd9f06d** this commit and test it, but it's so weird... Kaku can run it.
It have still have same problem, first build will fail, need run `npm rebuild`.

![](http://i.imgur.com/IXzfwPc.png)
